# Generated by Django 5.2.4 on 2025-12-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('stalking', 'Stalking'), ('eve_teasing', 'Eve Teasing'), ('cyber', 'Cyber Harassment'), ('workplace', 'Workplace Harassment'), ('abuse', 'Physical Abuse')], max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('story_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
