# Generated by Django 5.2.4 on 2025-12-10 08:37

import django.db.models.deletion
import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=stories.models.evidence_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='evidence/thumbnails/')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='stories.story')),
            ],
        ),
    ]
